name: NationStates AutoTelegram

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  bot:

    runs-on: ubuntu-latest

    steps:

      - name: Get repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: pip install requests

      - name: Run NationStates bot
        env:
          NS_CLIENT_KEY: ${{ secrets.NS_CLIENT_KEY }}
          NEW_NATIONS_TGID: ${{ secrets.NEW_NATIONS_TGID }}
          NEW_NATIONS_SECRET: ${{ secrets.NEW_NATIONS_SECRET }}
          NEW_WA_TGID: ${{ secrets.NEW_WA_TGID }}
          NEW_WA_SECRET: ${{ secrets.NEW_WA_SECRET }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: python bot.py

      - name: Save bot state
        run: |
          git config user.name "NationStates Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json
          git diff --cached --quiet || git commit -m "Update bot state"
          git push
